[package]
name = "scrape_blogger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
fs2 = "0.4.3"
indicatif = "0.17.8"
regex = "1.10.6"
reqwest = { version = "0.12.7", features = ["blocking"] }
scraper = "0.20.0"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
